create or replace TABLE USER_INTERACTIONS (
	INTERACTION_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0),
	SESSION_ID VARCHAR(255),
	INTERACTION_TYPE VARCHAR(50),
	INTERACTION_DATE TIMESTAMP,
	PRODUCT_ID NUMBER(38,0),
	PAGE_URL VARCHAR(500),
	SEARCH_QUERY TEXT,
	ADDED_TO_CART BOOLEAN DEFAULT FALSE,
	PURCHASE_COMPLETED BOOLEAN DEFAULT FALSE,
	DURATION_SECONDS INTEGER,
	primary key (INTERACTION_ID),
	foreign key (CUSTOMER_ID) references STREAM_HACKATHON.STREAMLIT.CUSTOMER_DETAILS(CUSTOMER_ID),
	foreign key (PRODUCT_ID) references STREAM_HACKATHON.STREAMLIT.PRODUCTS(PRODUCT_ID)
);

