create or replace TABLE CUSTOMER_DETAILS (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(20),
	ADDRESS VARCHAR(255),
	REGISTRATION_DATE DATE,
	FIRST_PURCHASE_DATE DATE,
	LAST_PURCHASE_DATE DATE,
	TOTAL_PURCHASE_COUNT INTEGER DEFAULT 0,
	TOTAL_PURCHASE_AMOUNT NUMBER(10,2) DEFAULT 0,
	LOYALTY_LEVEL VARCHAR(50),
	AVERAGE_ORDER_VALUE NUMBER(10,2),
	primary key (CUSTOMER_ID)
);